name: Compile solution

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  compile:
    uses: Abstrakcionist/revit-build-infrastructure/.github/workflows/Compile.yml@main
    secrets: inherit